### ISSUE TITLE
[Feature request]: assert array's length

### ISSUE THREAD

**Issue by SteveLauC** [infinilabs/loadgen#7]
For a JSON response like:

```
{
  "user_ids": [1, 2, 3]
}
```

I want to be able to assert `user_ids`'s length:

```
assert:
  length_equals:
    _ctx.response.user_ids: 3
```

**Comment by medcl** [comment]
Gonna use `length` in short, besides array length, string supported as well.

**Comment by SteveLauC** [comment]
> Gonna use `length` in short, besides array length, string supported as well.

Looks good
